export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_GIFS_SUCCESS = 'LOAD_GIFS_SUCCESS';
export const UPDATE_GIFS_SUCCESS = 'UPDATE_GIFS_SUCCESS';

export const LOAD_HISTORY_SUCCESS = 'LOAD_HISTORY_SUCCESS';
export const UPDATE_HISTORY_SUCCESS = 'UPDATE_HISTORY_SUCCESS';
